version: '2'
services:
  emma-web:
    image: nginx:1.13
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../app/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx.key:/etc/nginx/ssl/nginx.key
    network_mode: host
